version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - deploy/app/.env
    depends_on:
      - db
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n

  db:
    image: postgres:15
    container_name: n8n_postgres
    env_file:
      - deploy/app/.db-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: {}
  n8n_data: {}
