apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: prod
#spec:
#  ports:
#    - port: 5678
#      targetPort: 5678
#  selector:
#    app: n8n
#  type: LoadBalancer
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pv-claim
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-pv-claim

      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n

      containers:
        - name: n8n
          image: n8nio/n8n:1.89.2
          ports:
            - containerPort: 5678
              name: n8n
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: n8n-db-service
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n_db
            - name: DB_POSTGRESDB_USER
              value: n8n
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-env
                  key: DB_PASSWORD
            - name: N8N_SECURE_COOKIE
              value: "false"
          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n
