apiVersion: v1
kind: Service
metadata:
  name: n8n-db-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: n8n-db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-db-pv-claim
  namespace: prod
  labels:
    app: n8n-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-db-deployment
  namespace: prod
  labels:
    app: n8n-db
spec:
  selector:
    matchLabels:
      app: n8n-db
  template:
    metadata:
      labels:
        app: n8n-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: n8n_db
            - name: POSTGRES_USER
              value: n8n
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-env
                  key: DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: n8n-db-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: n8n-db-persistent-storage
          persistentVolumeClaim:
            claimName: n8n-db-pv-claim
