name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----  KUBERNETES: BUILD and PUBLISH --------------------------#
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'GKE Credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'n8n'
          location: 'asia-southeast2-a'

      - name: 'Deploy to GKE'
        run: |
          kubectl apply -f deploy/k8s -n prod

